import Head from "next/head";

import { Inter } from "@next/font/google";
import { Box, Flex } from "@chakra-ui/react";
import Navbar from "../components/Navbar";
import Banner from "../components/Entry/Banner";
import Strategy from "../components/Entry/Strategy";
import TrustWorthy from "../components/Entry/TrustWorthy";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Poppins&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <main>
        <Flex flexDirection='column' maxW={{md:'1200px'}}  mx="auto">
          <Navbar />
          <Banner />
          <Strategy/>
          <TrustWorthy/>
        </Flex>
      </main>
    </>
  );
}
